(* `cronyx.lock`: what resolution decided, written down so that a green build
   stays green. Checked in for binaries and for libraries both -- omitting it
   for libraries saves nothing and makes a bug report irreproducible.

   Written deterministically, because the alternative is diff churn in every
   repository that has one: packages sorted by name, dependencies sorted, and
   no field whose value depends on when or where the build ran. *)

open Bootstrap

let file_name = "cronyx.lock"

let render (r : Resolution.t) =
  let buffer = Buffer.create 256 in
  Buffer.add_string buffer "# Generated by cx. Check this in.\n";
  Buffer.add_string
    buffer
    (Printf.sprintf "cronyx = \"%s\"\n" (Version.to_string r.Resolution.cronyx));
  List.iter
    (fun (p : Resolution.entry) ->
      Buffer.add_string buffer "\n[[package]]\n";
      Buffer.add_string buffer (Printf.sprintf "name = \"%s\"\n" p.Resolution.name);
      Buffer.add_string
        buffer
        (Printf.sprintf "version = \"%s\"\n" (Version.to_string p.Resolution.version));
      Buffer.add_string buffer (Printf.sprintf "source = \"path+%s\"\n" p.Resolution.source);
      Buffer.add_string
        buffer
        (Printf.sprintf
           "dependencies = [%s]\n"
           (String.concat ", " (List.map (Printf.sprintf "\"%s\"") p.Resolution.dependencies))))
    r.Resolution.packages;
  Buffer.contents buffer

let path root = Filename.concat root file_name

let read root =
  match In_channel.with_open_bin (path root) In_channel.input_all with
  | text -> Some text
  | exception Sys_error _ -> None

let write root text =
  Out_channel.with_open_bin (path root) (fun out -> Out_channel.output_string out text)
