"""Regenerate lib/char_width.ml from the Unicode data Python was built with.

    python3 tools/gen_char_width.py > lib/char_width.ml
"""

import unicodedata


def zero_width(code):
    return (
        unicodedata.category(chr(code)) in ("Mn", "Me")
        or code in (0x200B, 0x200C, 0x200D, 0xFEFF)
        or 0xFE00 <= code <= 0xFE0F
        or 0xE0100 <= code <= 0xE01EF
    )


def wide(code):
    return unicodedata.east_asian_width(chr(code)) in ("W", "F")


def ranges(holds):
    found, start = [], None
    for code in range(0x110000):
        ok = False if 0xD800 <= code <= 0xDFFF else holds(code)
        if ok and start is None:
            start = code
        elif not ok and start is not None:
            found.append((start, code - 1))
            start = None
    if start is not None:
        found.append((start, 0x10FFFF))
    return found


def table(name, found):
    lines = [f"let {name} ="]
    lines.append("  [| " + "\n   ; ".join(
        "; ".join(f"0x{first:04X}, 0x{last:04X}" for first, last in found[at : at + 4])
        for at in range(0, len(found), 4)
    ) + "\n  |]")
    return "\n".join(lines)


print(f"""(* Generated by tools/gen_char_width.py from Unicode {unicodedata.unidata_version}.
   Edit the generator, not this file. *)
""")
print(table("zero_width", ranges(zero_width)))
print()
print(table("wide", ranges(wide)))
print("""
let holds table code =
  let low = ref 0 and high = ref (Array.length table - 1) and found = ref false in
  while (not !found) && !low <= !high do
    let middle = (!low + !high) / 2 in
    let first, last = table.(middle) in
    if code < first then high := middle - 1 else if code > last then low := middle + 1 else found := true
  done;
  !found

(* Columns a terminal draws the character in: none for a combining mark, two for
   the East Asian wide and fullwidth ranges, one for everything else. *)
let of_uchar scalar =
  let code = Uchar.to_int scalar in
  if holds zero_width code then 0 else if holds wide code then 2 else 1""")
